### ISSUE TITLE
Server crash related to Custom Portals

### ISSUE THREAD

**Issue by ThatScar** [Palyon-dev/CustomPortals#10]
I think it's in the API used but I'm reporting it here as well.
All the info is in this issue on the API:
https://github.com/kyrptonaught/customportalapi/issues/32

**Comment by Palyon-dev** [comment]
Custom Portals does not use Kyrptonaught's customportalapi, and the two mods are unrelated. Their similar names are purely coincidental.

**Comment by ThatScar** [comment]
Oh, my bad! I was browsing some other issue and I understood the resolution as "the problem is not in this mod but in the API" so I thought the API was related but it instead said it _wasn't related._
Oops!
