### ISSUE TITLE
[Feature Request] - Permissions for using the portals & creating portals ( LuckPerms )

### ISSUE THREAD

**Issue by xR4YM0ND** [Palyon-dev/CustomPortals#12]
Hey there, can you make permissions for this awesome portal mod

Permissions for using the Portals ( example permission: customportals.use )

Permissions for creating Portals ( example permission: customportals.create ) 

https://github.com/lucko/fabric-permissions-api

https://www.curseforge.com/minecraft/mc-mods/luckperms

**Comment by Palyon-dev** [comment]
Will look into this

**Comment by Palyon-dev** [comment]
I haven't gotten any other requests for this and at this point it's probably just not going to happen. Sorry

**Comment by xR4YM0ND** [comment]
No problem. Thank you for consider.
