### ISSUE TITLE
[Feature Request] — Let Create Mod Trains Connect to Custom Portals

### ISSUE THREAD

**Issue by Frankiscophil** [Palyon-dev/CustomPortals#15]
Hello! I'd just like to say first off that this mod is quite a great transportation method! Been trying to find an up-to-date multidimensional portal mod so discovering this was quite nice. And the fact that you can make portals out of any material block is a plus on customization so I was really happy with that!

I think it would be really cool too if this mod could also become compatible with the Create mod's ability to connect train tracks to portals for the potential of a multidimensional railway which I really would love to make. 

Thanks for reading my request and I hope you all have a good day now.

**Comment by Palyon-dev** [comment]
Hello--
Thanks for the kind words! I've gotten a few requests for this before on the CurseForge page. I've looked into it, and it quickly became clear to me that implementing compatibility with Create trains would be a deceptively big undertaking that I'm not willing to commit to at this time. Sorry to disappoint :/

**Comment by ajaxnotmeta** [comment]
cant we use customportal Api?/datapack portal APi thing? as a compat? i heard theres compat for that Datapack portals with create trains
