### ISSUE TITLE
Exiting Portals only Spawn Facing North

### ISSUE THREAD

**Issue by telriche** [Palyon-dev/CustomPortals#17]
When I go through portals they only spawn me in facing north each time. I could have sworn previous versions had a more custom facing when you spawn/exit a portal, which I think was based on how you were facing when the portal was placed. Since we can tag a block as the exit/spawn point, could we also affect the spawn direction with that mechanic?

**Comment by Palyon-dev** [comment]
Thanks for bringing this to my attention. You're supposed to stay facing the way you already were after teleporting, but it looks like something I changed in the last version broke this and I didn't notice. Just uploaded a fix on the CurseForge & Modrinth pages.
