### ISSUE TITLE
[Feature]: Clear Portal?

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [Palyon-dev/CustomPortals#18]
Possible a portal that is no specific color, but it is completely invisible (aside from hitbox showing of course), no color, texture, or particles. Could require dragons breath or a golden carrot instead of a dye in the middle.

**Comment by Palyon-dev** [comment]
Sorry for taking forever to get back to you on this lol--This isn't really a feature I'm interested in adding to be honest, but I see you've taken the initiative of forking my code and adding it yourself. I respect it!
