### ISSUE TITLE
Interdimensional portal for custom dimension only works one way

### ISSUE THREAD

**Issue by campbebj** [Palyon-dev/CustomPortals#2]
Hey, Im testing out this mod for possible use in my next world and ive found that if i have custom dimension (multiple overworlds) the portals dont work two ways interdimensionally.
I can put a portal in both dimensions but it only works from the custom dimension back to the main overworld. it doesn't let me return to the custom dimension.

**Comment by Palyon-dev** [comment]
Sorry for the late response; what are you using to generate the multiple overworlds? Is it just a datapack?

**Comment by Palyon-dev** [comment]
Closing this due to lack of information and since no one else has had this issue
