### ISSUE TITLE
My backpack from "Traveler's Backpack" mod is missing after teleporting.

### ISSUE THREAD

**Issue by SamRedFox** [Palyon-dev/CustomPortals#20]
I can't access my backpack after using a custom portal. The problem is not present with regular and other modded portals such as "The Twilight forest". To fix the problem I enter and exit other portals not related to this mod.

**Comment by SamRedFox** [comment]
The problem is solved. "YDM's Weapon Master" was causing this glitch. I also had crashes from time to time after entering portals. Turns out all the problems are because of this "YDM's Weapon Master" mod.

**Comment by SamRedFox** [comment]
Nevermind, backpacks are still glitching after using portals. But at least my game is not crashing anymore :/

**Comment by Palyon-dev** [comment]
Will look into this

**Comment by Palyon-dev** [comment]
Which backpack mod are you using?

**Comment by Palyon-dev** [comment]
Unable to reproduce. Tested entering both intra- and interdimensional portals with multiple different backpacks from Traveler's Backpack equipped and did not encounter any issues. The backpack is still on my back after teleporting, is still accessible, and all items and fluids stored inside are still intact. If you are still encountering this problem, please reopen this issue with more information on how to reproduce.
