### ISSUE TITLE
[Idiot User] Server won't start with the mod

### ISSUE THREAD

**Issue by Lazyvibess** [Palyon-dev/CustomPortals#22]
I don't know why the server wont start when I have the mod installed and it doesn't even crash to generate a crash log so all I have is the server console to go off of and I dont know what the problem could be from it... I am new to using github issues sorry if I didnt do this correctly

[2023-12-25-7.log](https://github.com/Palyon-dev/CustomPortals/files/13767093/2023-12-25-7.log)

**Comment by Palyon-dev** [comment]
[Known issue with some versions of CompleteConfig.](url) Updating to v2.5.2 of CompleteConfig should fix the problem, otherwise you'll need to go back to version 0.14.25 of your Fabric Loader (not sure if CompleteConfig v2.5.2 is compatible with Minecraft 1.20.1)
