### ISSUE TITLE
[Crash] Version 1.20.1 needs CompleteConfig 2.5.2 or higher

### ISSUE THREAD

**Issue by xR4YM0ND** [Palyon-dev/CustomPortals#24]
2.5.0 is the latest completeconfig for 1.20.1

but v3.3.0 customportals needs 2.5.2 or above which isnt for 1.20.1

**Comment by Palyon-dev** [comment]
I've tested it and completeconfig 2.5.2 and 2.5.3 are also compatible with Minecraft 1.20.1 despite what it says. I require v2.5.2 or higher of completeconfig because versions before that have a compatiblity issue with the latest version of the Fabric loader.
