### ISSUE TITLE
Using portal breaks game mode switcher and Easy Shilker Boxes' preview

### ISSUE THREAD

**Issue by Silenc42** [Palyon-dev/CustomPortals#27]
I am OP on my online fabric server v1.20.4. After going through the portal, two noticable problems appear; I *think* they have a similar cause related to player state on the server.
I use a portal with the strong enhancer rune, with both end in the overworld.

Problems:
- I can no longer access the game mode switcher (F3+F4).
- Easy Shulker Box mod no longer correctly shows the content of shulkers, ender chests, etc.

I'd appreciate any assistance. Feel free to contact me with any questions.

**Comment by Silenc42** [comment]
It also makes it seem like I have no xp after going through a portal from this mod. Once I gain some, I "regain" the xp that seemed gone.

**Comment by Silenc42** [comment]
Traveling to another dimension remedies the issue. Both vanilla portals and custom portals work for this purpose.

**Comment by Palyon-dev** [comment]
Fixed on v3.4.1
