### ISSUE TITLE
How to use + how to make?

### ISSUE THREAD

**Issue by pil0lo** [Palyon-dev/CustomPortals#30]
The portal is not created.
![1](https://github.com/Palyon-dev/CustomPortals/assets/143984023/08a24dbc-f019-4d7a-993a-acea254efc14)

How should I use runes?
![2](https://github.com/Palyon-dev/CustomPortals/assets/143984023/ae34cf19-bfdb-439d-9d41-1f5642254903)

**Comment by Palyon-dev** [comment]
Oh whoops. Apparently the "recipes" directory has to be named "recipe" without an s for 1.21. Just uploaded a new version that should fix this and make everything craftable again.

Runes will be applied to your portals when they're placed on one of the portal frames.
