### ISSUE TITLE
lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'serverbound/minecraft:set_creative_mode_slot' 

### ISSUE THREAD

**Issue by MegaFTFW** [Palyon-dev/CustomPortals#31]
lost connection: Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'serverbound/minecraft:set_creative_mode_slot'

get this error whenever i try to put one of the customportal items in my inventory in creative mode

**Comment by Palyon-dev** [comment]
Which version are you using?

**Comment by Palyon-dev** [comment]
Closing this due to not enough information & unable to reproduce
