### ISSUE TITLE
Gamemode Switcher breaks after entering Custom Portal

### ISSUE THREAD

**Issue by greglor** [Palyon-dev/CustomPortals#32]
![image](https://github.com/user-attachments/assets/5220dfec-eaf0-4a56-94cd-ba10a48d3e38)

The game mode switcher works until I enter a custom portal, then all of a sudden it acts like cheats are off.

**Comment by greglor** [comment]
It also takes away most OP permissions, like opening command blocks etc. A quick fix for it is to open to LAN and reenable cheats, but that shouldn't be necessary when cheats are already enabled.

**Comment by Palyon-dev** [comment]
Which version are you using? I tried this on the latest version for MInecraft 1.21 and it seems to work fine

**Comment by greglor** [comment]
1.20.1 Fabric

**Comment by Palyon-dev** [comment]
Finally got around to fixing this on v3.4.1
