### ISSUE TITLE
Portals not actually working

### ISSUE THREAD

**Issue by G3rgie** [Palyon-dev/CustomPortals#4]
I can create portals using the portal crystals and selected block, but then the portal doesnt actually work when I try to go thru it.

**Comment by Palyon-dev** [comment]
Did you create two matching portals or just one? You need to build two portals out of the same block and with the same color catalyst, then they'll automatically link up. If you just build one portal it won't do anything.

**Comment by Palyon-dev** [comment]
I'm going to assume you misunderstood what the mod does and only made one portal, and go ahead and close this. If you did make two portals out of the same materials and they still didn't work, please make a new issue describing the problem and how to reproduce it.
