### ISSUE TITLE
Crashes Server

### ISSUE THREAD

**Issue by milkev** [Palyon-dev/CustomPortals#5]
**Mod Versions**
Cardinal Components 3.0.0
Custom Portals 2.0.0
Fabric API 0.36
Fabric Loader 0.11.6
Minecraft 1.17 Dedicated Server

**The Issue**
When loading a server with custom portals (and dependencies) it crashes.
I believe the specific problem is from this line `Cannot load class me.lortseam.completeconfig.gui.ConfigScreenBuilder in environment type SERVER`

**Server Log**
[latest.log](https://github.com/Palyon-dev/CustomPortals/files/6710243/latest.log)

**Comment by Palyon-dev** [comment]
Knew there was something I'd forgotten to test. Should be fixed in the new version.
