### ISSUE TITLE
[Feature request] Whitelist and/or tag for portal frame blocks

### ISSUE THREAD

**Issue by Danklor** [Palyon-dev/CustomPortals#6]
I'd like to be able to be able to specify a special block that needs to be used to build the portal frame rather than just any block. I have an idea for a technical modpack where using modded:superconducting_coils would make more sense than minecraft:dirt.

**Comment by Palyon-dev** [comment]
Not a bad idea. I'll look into implementing this

**Comment by Palyon-dev** [comment]
This feature is now in the latest version.
