### ISSUE TITLE
I cant go through to another dimension (1.16.5)

### ISSUE THREAD

**Issue by mhxr7** [Palyon-dev/CustomPortals#8]
I can create portals using the portal crystals and selected block, but then the portal doesn't actually work when I try to go thru it. the portal animation creates  but i cant go thru. even when i used the same colour catalyst.
![2021-08-18_10 17 54](https://user-images.githubusercontent.com/89120335/129838640-e0a37817-c590-419d-89d8-b4fcaf2e6f13.png)
![2021-08-18_10 18 00](https://user-images.githubusercontent.com/89120335/129838643-ec443e06-18fb-43d4-8e2c-569ab0808228.png)

**Comment by Palyon-dev** [comment]
This is not a dimension mod; it's a transportation mod. The point is to make two portals out of the same block and color, which will allow you to travel between them. Creating only one portal without creating a second one for it to link to will not do anything. This mod does not add any new dimensions.
